version: "3.9"

networks:
  app-network:
    driver: bridge

x-services-volume: &services-volume
  type: bind
  source: ${APPLICATION_FOLDER}
  target: /var/www/html

services:
  nginx:
    build:
      context: ./images/nginx
      dockerfile: nginx.dockerfile
      args:
        - HOST_UID=${HOST_UID:-1001}
        - HOST_GID=${HOST_GID:-1001}
    container_name: "${CONTAINER_PREFIX}-nginx"
    restart: unless-stopped
    ports:
      - "8085:${NGINX_INTERNAL_PORT}"
      - 443:443
    volumes:
      - <<: *services-volume
      - ./images/nginx/certs:/etc/nginx/ssl
    networks:
      - app-network
